server:
  port: 8080

spring:
  data:
    mongodb:
      host: 
      port: 
      database: 
      username: 
      password: 

logging:
  level:
    org.springframework.data: DEBUG
    com.mongodb: DEBUG